### PR TITLE
[#380] As a developer, I can see the App Icon after generating the project [develop]

### LINKED ISSUE #380: As a developer, I can see the App Icon after generating the project
## Why

Currently, we can not upload a build to TestFlight after generating the project because of App Icon. I think it is better to have an App Icon after generating the project.

## Acceptance Criteria

- Setup the app icon while generating a new project
- Use our logo for the app icon: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

## Design

Nimble Logo: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

### PR DESCRIPTION
**Pull request by blyscuit**
- #380 

## What happened

Add app icon to template.

## Insight

- Remove app icon from TestFlight testing.
- Use `Single App Icon` supported for Xcode 14. 
 
## Proof Of Work

Screen Shot 2022-12-20 at 12 13 08

New icon on Testflight.

### CODE REVIEW

**Review by ducbm051291 — APPROVED** [review]

**Review by suho — APPROVED** [review]

**Comment by markgravity** [comment]
@blyscuit we have a duplicated PR 🤔 
Screenshot 2022-12-20 at 15 34 20

**Comment by blyscuit** [comment]
@markgravity One for `migrate-develop`, one for `develop`, currently they have completely different base, and both would benefit from the feature.

**Review by nkhanh44 — APPROVED** [review]

**Comment by vnntsu** [comment]
> @markgravity One for `migrate-develop`, one for `develop`, currently they have completely different base, and both would benefit from the feature.

I think we will soon merge `migrate-develop` to `develop`. Do you think we really need to merge this? I'm just afraid of conflicts later.

**Comment by blyscuit** [comment]
> > @markgravity One for `migrate-develop`, one for `develop`, currently they have completely different base, and both would benefit from the feature.
> 
> I think we will soon merge `migrate-develop` to `develop`. Do you think we really need to merge this? I'm just afraid of conflicts later.

This fixes CICD workflow on develop as well, but if merging `migrate` soon then no need this one. 👍

**Review by Shayokh144 — APPROVED** [review]

**Pull request closed without merging**
