### PR TITLE
[#255] Update Tuist version - 3.x

### LINKED ISSUE #255: Update Tuist version - 3.x
## Why

Our Tuist setup is using outdated APIs - version [2.x](https://docs.tuist.io/2/tutorial/get-started), we need to use the latest version [3.x](https://docs.tuist.io/tutorial/get-started).

## Acceptance Criteria

- Update the version in `.tuist-version` to 3.0.1
- We can generate the templates without issues

## Resources

[Tuist 3.0.1](https://github.com/tuist/tuist/releases/tag/3.0.1)

### PR DESCRIPTION
**Pull request by blyscuit**
close #255 

## What happened

- Update the version in `.tuist-version` to 3.2.0
- We can generate the templates without issues

  
## Insight

Follow release notes on https://github.com/tuist/tuist/releases.

Move `Config.swift` to `Workspace.swift` and `Project.swift`.
 
There's a bug for Sourcery https://github.com/krzysztofzablocki/Sourcery/issues/1058 so test might fail.

## Proof Of Work
Screen Shot 2022-04-26 at 15 52 55
Screen Shot 2022-04-26 at 15 50 38

### CODE REVIEW

**Review by markgravity — APPROVED** [review]
LGTM 👏

**Comment by blyscuit** [comment]
Build is failing because the bug in Sourcery, 1.8.1 should already be removed not sure why GH Actions is still pointing to 1.8.1.

**Comment by blyscuit** [comment]
Build success when force Sourcery to 1.8.0 but this won't scale well. 
Screen Shot 2022-04-27 at 11 40 08

**Comment by suho** [comment]
@blyscuit How about pointing to `1.8.0` in the Podfile? I also get the same error when running `pod install` on my mac

**Comment by blyscuit** [comment]
> @blyscuit How about pointing to `1.8.0` in the Podfile? I also get the same error when running `pod install` on my mac

I don't think this is a good solution, I think the template should be using the newest version rather than fixing to a specific version. Using too old version might cause future project to fail to build for no reason.

**Comment by suho** [comment]
@blyscuit One concern, how can we install the Sourcery with version 1.8.1? or wait for a fix from Sourcery?

**Comment by blyscuit** [comment]
> @blyscuit One concern, how can we install the Sourcery with version 1.8.1? or wait for a fix from Sourcery?

We have to specify `1.8.0` locally when building. Sorry if I misunderstood your first question. 🙇

**Comment by suho** [comment]
@blyscuit I still prefer making CI work normally first by updating the Podfile like this:
```rb
// TODO: Remove or update the version of `1.8.0` to the newest version (not 1.8.1) when init a new project.
// Currently, there is a bug with `1.8.1` - the newest version.
pod 'Sourcery', '1.8.0'
```

What do you think? I can create a pull request to make a quick fix for this issue #269

**Comment by blyscuit** [comment]
> @blyscuit I still prefer making CI work normally first by updating the Podfile like this:
> 
> ```ruby
> # TODO: Remove or update the version of `1.8.0` to the newest version (not 1.8.1) when init a new project.
> # Currently, there is a bug with `1.8.1` - the newest version.
> pod 'Sourcery', '1.8.0'
> ```
> 
> What do you think? I can create a pull request to make a quick fix for this issue #269

Sure, let's go with that.

**Review by suho — APPROVED** [review]
LGTM

**Pull request merged**
