### PR TITLE
[#380] As a developer, I can see the App Icon after generating the project

### LINKED ISSUE #380: As a developer, I can see the App Icon after generating the project
## Why

Currently, we can not upload a build to TestFlight after generating the project because of App Icon. I think it is better to have an App Icon after generating the project.

## Acceptance Criteria

- Setup the app icon while generating a new project
- Use our logo for the app icon: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

## Design

Nimble Logo: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

### PR DESCRIPTION
**Pull request by blyscuit**
- close #380 

## What happened

Add app icon to template.

## Insight

- Remove app icon from TestFlight testing.
- Use `Single App Icon` supported for Xcode 14. 
 
## Proof Of Work

Screen Shot 2022-12-20 at 12 13 08

New icon on Testflight.

### CODE REVIEW

**Comment by suho** [comment]
@blyscuit Please change the base branch to `develop` :D

**Comment by vnntsu** [comment]
@nkhanh44 @blyscuit what do you think if we change base to `migrate-develop`? I think @nkhanh44 is working on this too.

**Comment by nkhanh44** [comment]
@vnntsu It's good to do since the appicon plugin broke in Fastlane swift 🙏 .

**Comment by ducbm051291** [comment]
I agree with @vnntsu to change the base to `migrate-develop`

**Pull request closed without merging**
